## ATTRIBUTE AMPLIFIERS ##

# general attribute settings
# *..required
# active: enable (true) or disable (false) an amplifier
#         default: true
# in-percent: use percentage values (true) or absolut values (false)
#             default: true
# range*: the range of an amplifier.
#        two numbers in brackets or single number for a fixed value
# ignore-items: list of items that should be ignored only for the amplifier
#               empty by default
# chance: the chance an amplifier can be applied
#         number in percent between 1 and 100
#         default: 100
# tools-and-weapons: amplifier being applied on tools and weapons (true/false)
#                    default: true
# armor-and-shield: amplifier being applied on armor and shield (true/false)
#                   default: true
# use-only-natural-numbers: range values will only use natural numbers with no floating points (true/false)
#                           default: true
#                           note: if the range contains a float this will be overwritten to false

durability:
  active: true
  in-percent: true
  range: [ -30, 30 ]
  chance: 100
  ignore-items: [ ]
  tools-and-weapons: true
  armor-and-shield: true
  use-only-natural-numbers: true

attack-damage:
  active: true
  in-percent: true
  range: [ -30, 30 ]
  chance: 100
  ignore-items: [ ]
  tools-and-weapons: true
  armor-and-shield: false
  use-only-natural-numbers: true

max-health:
  active: true
  in-percent: false
  range: [ -6, 6 ]
  chance: 100
  ignore-items: [ ]
  tools-and-weapons: false
  armor-and-shield: true
  use-only-natural-numbers: true

## SETTINGS ##

# items from loot tables being modified
# default: true
use-loot-tables: true

# items from mob drops being modified
# default: true
use-mob-drops: true

# items traded from villager being modified
# default: true
use-villager-trades: true

# items crafted being modified
# default: true
use-crafting: true

# ignore items for all attributes
# empty by default
ignore-items: [ ]